---
- name: Update system and reboot if necessary
  hosts: all
  become: true

  tasks:
  - name: Update all installed packages
    ansible.builtin.package:
      name: '*'
      state: latest
    register: dnf_update_status

  - name: Reboot system when packages were updated
    ansible.builtin.reboot:
      reboot_timeout: 300
    when: dnf_update_status.changed